* Что почти лишнее
  - [ ] mrt:iron-router-progress - прогресбоарчик загрузки страницы как в гугле
    - [ ] добавить в исключение роуты загрузка которых и так быстрая
  - [ ] alethes:pages -- pagination на bootstrap.

* Что реализовать [1/3]
  - [X] Авторизация по смс.
  - [ ] [0/3] Профиль юзера.
    - [ ] Роли юзера (админ, клиент, исполнитель, также клиент может быть исполнителем)
    - [ ] Аплоад картинок для фрофиля, наверное по проектам структурировать
    - [ ] Аватарочка, как в хипсторах? кругленькая такая
    - [ ] Категории специализации, нужно скопипастить у конкурентов
    - [ ] Лента профилей.
  - [ ] Лента.. в далеком будущем
    - [ ] Обявление.

* Деплоинг и настройка

  Ниже смотря для чего, девелоп или продакшн мод

** Девелоп

   Чтобы не тратится на СМСки, и чтобы реестрация работала, установить
   переменную SMSC_AUTH  в любое значение но  не настраивать MAIL_URL.
   Тогда  email-ы   будут  высыпаться  в  консольку,   так  как  емейл
   (MAIL_URL) не настроены. Короч запускаем так

#+begin_example
SMSC_AUTH=foo:bar meteor
#+end_example

** Продакшн

#+begin_example
SMSC_AUTH=ononos:mycoolemail \
MAIL_URL=smtp://olexandr.syd%40gmail.com:emailpasswordhere@smtp.gmail.com:465/ \
meteor
#+end_example
