* Что почти лишнее
  - [ ] mrt:iron-router-progress - прогресбоарчик загрузки страницы как в гугле
    - [ ] добавить в исключение роуты загрузка которых и так быстрая
  - [ ] alethes:pages -- pagination на bootstrap.

* Что реализовать [1/4]
  - [X] Авторизация по смс.
  - [-] [4/10] Профиль юзера.
    - [X] Роли юзера (админ, клиент, исполнитель, также клиент может быть исполнителем)
    - [X] Аплоад картинок для фрофиля, наверное по проектам структурировать
    - [ ] Добавить поля "Стоимость" и "Сроки" к работам в портфолио
    - [ ] Добавить разделение работ в портфолио по категориям. Поклейка обоев/монтаж унитазов/покраска стен и т.д.
      Список категорий редактируется через админку (можно добавлять/удалять/переименовывать).
      Дефолтная категория - "Прочие виды работ". Присваивается работе, если пользователь не выбрал категорию добавляемой работы или выбрал данный пункт специально.
    - [ ] В пакете mol-uploads/avatar.styl сконвертить в less чтобы не быть зависимим от styl пакета
    - [X] Аватарочка, как в хипсторах? кругленькая такая
    - [ ] Категории специализации, нужно скопипастить у конкурентов.
      Скорей всего такие же категории что и для портфолио
    - [ ] Лента профилей.
    - [X] QR code - добавление контактов в телефон через qr код на странице профиля юзера
    - [ ] Город/регион юзера. По нем будет поумолчанию поиск обьявлений. Для мастера важно.

  - [ ] Нотификация.
    - [ ] СМС нотификация
    - [ ] e-mail нотификация
    - [ ] и сюда ж, сообщения между юзерам, техподдержкой
  - [ ] Лента.. в далеком будущем
    - [ ] Обявление.
    - [ ] каталог мастеров

* Сопровождение

  В этом разделе все что нужно знать для сопровождения сайта

** Города

   Список городов/регионов в файлах `private/cities-*.org`.  Пока нет
   механизма  миграции, если  город сменил  название/перешел в  другую
   страну (привет  Крым) придется писать  миграцию и уж  потом править
   эти `.org` файлы. Смотри [[file:server/cities.js]].

* Деплоинг и настройка

  Ниже смотря для чего, девелоп или продакшн мод

  Админ будет создан с номером телефона =380123456789= и паролем =admin=.

** Продакшн

Нужно установить SMSC_AUTH (cmsc.ru логин и пароль) и MAIL_URL переменные:

Чтобы определение айпи работало нужно также установить HTTP_FORWARDED_COUNT
в зависимости от количеста проксей/лоадбалансеров (например, если метеор
за nginx то HTTP_FORWARDED_COUNT=1).

Итого пример:

#+begin_example
HTTP_FORWARDED_COUNT=1
SMSC_AUTH=ononos:mypassword \
MAIL_URL=smtp://olexandr.syd%40gmail.com:emailpasswordhere@smtp.gmail.com:465/ \
meteor
#+end_example
