* Что почти лишнее
  - [ ] mrt:iron-router-progress - прогресбоарчик загрузки страницы как в гугле
    - [ ] добавить в исключение роуты загрузка которых и так быстрая
  - [ ] alethes:pages -- pagination на bootstrap.

* Что реализовать [2/7]
  - [X] Авторизация по смс.
  - [-] [9/12] Профиль юзера.
    - [X] Роли юзера (админ, клиент, исполнитель, также клиент может быть исполнителем)
    - [X] Аплоад картинок для фрофиля, наверное по проектам структурировать
    - [X] Добавить поля "Стоимость" и "Сроки" к работам в портфолио
    - [X] Добавить разделение работ в портфолио по категориям. Поклейка обоев/монтаж унитазов/покраска стен и т.д.
      Список категорий редактируется через админку (можно добавлять/удалять/переименовывать).      
    - [X] Цены услуг, шаблон, а также детальный. Особый пункт минимальный заказ.
    - [ ] Свои собственные позиции в прайсе, сейчас только то что админ наварганит. 
    - [ ] В пакете mol-uploads/avatar.styl сконвертить в less чтобы не быть зависимим от styl пакета
    - [X] Аватарочка, как в хипсторах? кругленькая такая
    - [X] Категории специализации, нужно скопипастить у конкурентов.
      Скорей всего такие же категории что и для портфолио
    - [X] QR code - добавление контактов в телефон через qr код на странице профиля юзера
    - [X] Город/регион юзера. По нем будет поумолчанию поиск обьявлений. Для мастера важно.
    - [ ] Перепилить категории, может с портфолио обьеденить

  - [ ] [0/3] Нотификация.
    - [ ] СМС нотификация (для чего?)
    - [ ] e-mail нотификация (для чего?)
    - [ ] и сюда ж, сообщения между юзерам, техподдержкой

  - [ ] [0/4] Лента обьявлений
    - [ ] Обявление.
    - [ ] Фильтр обьявлений, по умолчанию, или последний что юзер набирал(запомнить) или может история фильтров.
    - [ ] Где-то историю прилепить, чтобы быстро найти мог мастер что он смотрел.
    - [ ] Решить, нужно ли сохранять вечно обьявления, можно сделать чтобы автоматом удалялись спустя напр. 3месяц
      
  - [ ] [0/2] Каталог мастеров
    - [ ] Возможность добавить в фаворит, чтобы потом юзер мог быстро найти (сравнить?)
    - [ ] История последних просмотров мастеров. (так сможет быстрее найти)

  - [X] Разобратся с деплоингом meteor up. DOKKU все равно нам не подходит, сложный слишком.
    Вывод: Разобрался, не понравилось, осилил зато сборку по git-hooks, потыкал хипсторский passenger, говно, падает при нагрузках.
 
  - [ ] [0/7] Рефакторинг, переписать. Низкий приоритет.
    - [ ] Переделить маску для телефона, сделать маску 
      Для номеров +3 - +d (dddd) dd-ddd-ddd для остальных +d (ddd) ddd-dd-ddd
      Вот прикольная маска http://digitalbush.com/projects/masked-input-plugin/
    - [ ] Вместо методов, сделать  allow правила для  колекций. Очень
      много дублей в  методах, порядок навести нужно.  И события будет
      проще сделать нормально.
    - [ ] Переписать события, упростить.
    - [ ] Иземенения в профиле, както чтобы легче было следить за изменениями админу.
    - [ ] Переверстать/причесать виджеты input, textarea, select.
      Сейчас редактирование по doubleclick, нужно по одному.
      Наверное ховер сделать, чтобы кнопки редактирования появлялись при мышке наведении.
    - [ ] "Показать пароль" (как минимум в форме смене пароля)
    - [ ] Нужно подготовить шаблон загрузки (layouts/loading.html), 404

* Сопровождение

  В этом разделе все что нужно знать для сопровождения сайта

** Города

   Список городов/регионов в файлах `private/cities-*.org`.  Пока нет
   механизма  миграции, если  город сменил  название/перешел в  другую
   страну (привет  Крым) придется писать  миграцию и уж  потом править
   эти `.org` файлы. Смотри [[file:server/cities.js]].

* Деплоинг и настройка

  Ниже смотря для чего, девелоп или продакшн мод

  Админ будет создан с номером телефона =380123456789= и паролем =admin=.

** Девелопмент

*** Windows/Vagrant

    Пример Vagrant файла здесь: https://github.com/osv/win-vagrant-meteor.git
    Для старта внутри вагранта есть скрипт =start-vagrant.sh=

    То есть если этот каталог находится в =shared/stroim= следует сделать:

#+begin_example
vagrant up
vagrant ssh
cd ~/shared/stroim
./start-vagrant.sh
#+end_example
 
*** Экспорт/импорт

    Для экспорта-импорта есть следующие скрипты:

    Экспорт:
#+begin_example
./tool-dump.bash ~/shared/my-new-dump.tar.gz
#+end_example

    Импорт:
#+begin_example
./tool-restore.bash ~/shared/my-new-dump.tar.gz
#+end_example

** Продакшн

Нужно установить SMSC_AUTH (cmsc.ru логин и пароль) и MAIL_URL переменные:

Чтобы определение айпи работало нужно также установить HTTP_FORWARDED_COUNT
в зависимости от количеста проксей/лоадбалансеров (например, если метеор
за nginx то HTTP_FORWARDED_COUNT=1).

Итого пример:

#+begin_example
HTTP_FORWARDED_COUNT=1
SMSC_AUTH=ononos:mypassword \
MAIL_URL=smtp://olexandr.syd%40gmail.com:emailpasswordhere@smtp.gmail.com:465/ \
meteor
#+end_example
