* Что почти лишнее
  - [ ] mrt:iron-router-progress - прогресбоарчик загрузки страницы как в гугле
    - [ ] добавить в исключение роуты загрузка которых и так быстрая
  - [ ] alethes:pages -- pagination на bootstrap.

* Что реализовать [1/6]
  - [X] Авторизация по смс.
  - [-] [6/9] Профиль юзера.
    - [X] Роли юзера (админ, клиент, исполнитель, также клиент может быть исполнителем)
    - [X] Аплоад картинок для фрофиля, наверное по проектам структурировать
    - [X] Добавить поля "Стоимость" и "Сроки" к работам в портфолио
    - [ ] Добавить разделение работ в портфолио по категориям. Поклейка обоев/монтаж унитазов/покраска стен и т.д.
      Список категорий редактируется через админку (можно добавлять/удалять/переименовывать).
      Дефолтная категория - "Прочие виды работ". Присваивается работе, если пользователь не выбрал категорию добавляемой работы или выбрал данный пункт специально.
    - [ ] В пакете mol-uploads/avatar.styl сконвертить в less чтобы не быть зависимим от styl пакета
    - [X] Аватарочка, как в хипсторах? кругленькая такая
    - [ ] Категории специализации, нужно скопипастить у конкурентов.
      Скорей всего такие же категории что и для портфолио
    - [X] QR code - добавление контактов в телефон через qr код на странице профиля юзера
    - [X] Город/регион юзера. По нем будет поумолчанию поиск обьявлений. Для мастера важно.

  - [ ] [0/3] Нотификация.
    - [ ] СМС нотификация
    - [ ] e-mail нотификация
    - [ ] и сюда ж, сообщения между юзерам, техподдержкой

  - [ ] [0/2] Лента.. в далеком будущем
    - [ ] Обявление.
    - [ ] каталог мастеров

  - [ ] Разобратся с деплоингом meteor up. DOKKU все равно нам не подходит, сложный слишком.
 
  - [ ] [0/2] Рефакторинг, переписать. Низкий приоритет.
    - [ ] Переделить маску для телефона, сделать маску 
      Для номеров +3 - +d (dddd) dd-ddd-ddd для остальных +d (ddd) ddd-dd-ddd
    - [ ] Вместо методов, сделать  allow правила для  колекций. Очень
      много дублей в  методах, порядок навести нужно.  И события будет
      проще сделать нормально.

* Сопровождение

  В этом разделе все что нужно знать для сопровождения сайта

** Города

   Список городов/регионов в файлах `private/cities-*.org`.  Пока нет
   механизма  миграции, если  город сменил  название/перешел в  другую
   страну (привет  Крым) придется писать  миграцию и уж  потом править
   эти `.org` файлы. Смотри [[file:server/cities.js]].

* Деплоинг и настройка

  Ниже смотря для чего, девелоп или продакшн мод

  Админ будет создан с номером телефона =380123456789= и паролем =admin=.

** Девелопмент

   На windows, с Vagrant запускай скрипт:

#+begin_example
./start-vagrant.sh
#+end_example

** Продакшн

Нужно установить SMSC_AUTH (cmsc.ru логин и пароль) и MAIL_URL переменные:

Чтобы определение айпи работало нужно также установить HTTP_FORWARDED_COUNT
в зависимости от количеста проксей/лоадбалансеров (например, если метеор
за nginx то HTTP_FORWARDED_COUNT=1).

Итого пример:

#+begin_example
HTTP_FORWARDED_COUNT=1
SMSC_AUTH=ononos:mypassword \
MAIL_URL=smtp://olexandr.syd%40gmail.com:emailpasswordhere@smtp.gmail.com:465/ \
meteor
#+end_example
